export const productData = {
  product: {
    uid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    batch_uid: "VT-CAM-001-2026-Q2-BATCH-042",
    gtin: "8431234567890",
    name: "Camiseta Unisex Algodón Orgánico",
    name_en: "Unisex Organic Cotton T-Shirt",
    brand: "Vela Textile",
    category: "Prenda de vestir superior / Camiseta",
    category_en: "Upper garment / T-Shirt",
    size_range: "S-XXL",
    color: "Natural / Crudo",
    color_en: "Natural / Raw",
    season: "SS26",
    image_url: "/product-placeholder.jpg",
  },
  origin: {
    final_country: "España",
    final_country_en: "Spain",
    manufacturing_country: "Túnez",
    manufacturing_country_en: "Tunisia",
    facilities: [
      { stage: "Ginning", stage_en: "Ginning", name: "Anatolian Cotton Ginning Co.", location: "Adana, Turquía", location_en: "Adana, Turkey", coordinates: [37.0, 35.3] as [number, number], country: "TR" },
      { stage: "Hilatura", stage_en: "Spinning", name: "Fiação Moderna Lda.", location: "Guimarães, Portugal", location_en: "Guimarães, Portugal", coordinates: [41.4, -8.3] as [number, number], country: "PT" },
      { stage: "Tejeduría", stage_en: "Weaving", name: "Textiles de l'Atlas SARL", location: "Casablanca, Marruecos", location_en: "Casablanca, Morocco", coordinates: [33.6, -7.6] as [number, number], country: "MA" },
      { stage: "Confección", stage_en: "Manufacturing", name: "Confection du Sahel SA", location: "Monastir, Túnez", location_en: "Monastir, Tunisia", coordinates: [35.8, 10.8] as [number, number], country: "TN" },
      { stage: "Acabado", stage_en: "Finishing", name: "Acabados Textiles del Levante SL", location: "Valencia, España", location_en: "Valencia, Spain", coordinates: [39.5, -0.4] as [number, number], country: "ES" },
    ],
    production_start: "2026-03-15",
    production_end: "2026-04-02",
    batch_size: 2500,
    total_distance_km: 4850,
  },
  composition: {
    materials: [
      { name: "Algodón orgánico", name_en: "Organic cotton", percentage: 60, weight_g: 120, origin: "Turquía", origin_en: "Turkey", certification: "GOTS", source_evidence: "Certificación GOTS", source_evidence_en: "GOTS certification" },
      { name: "Poliéster reciclado", name_en: "Recycled polyester", percentage: 35, weight_g: 70, origin: "España", origin_en: "Spain", source: "Botellas PET posconsumo", source_en: "Post-consumer PET bottles", source_short: "PET posconsumo", source_short_en: "post-consumer PET", source_evidence: "Certificación GRS", source_evidence_en: "GRS certification" },
      { name: "Elastano", name_en: "Elastane", percentage: 5, weight_g: 10, origin: "Alemania", origin_en: "Germany", source_evidence: "Ficha técnica de composición", source_evidence_en: "Composition technical sheet" },
    ],
    chemical_treatments: [
      { es: "Tinte reactivo sin metales pesados", en: "Reactive dye, heavy metal free", source_evidence: "Ficha técnica de tintura", source_evidence_en: "Dyeing technical sheet", has_document: true },
      { es: "Suavizante a base de silicona de bajo impacto", en: "Silicone-based softener, low impact", source_evidence: "Ficha técnica de suavizante", source_evidence_en: "Softener technical sheet", has_document: true },
      { es: "Acabado enzimático de biopulido", en: "Enzymatic finish, bio-polishing", source_evidence: "Pendiente de carga", source_evidence_en: "Pending upload", has_document: false },
    ],
    svhc_status: "Ninguna sustancia SVHC presente",
    svhc_status_en: "No SVHC substances present",
    svhc_verification_date: "2026-02-01",
    svhc_source_evidence: "Declaración SVHC / REACH",
    svhc_source_evidence_en: "SVHC / REACH declaration",
    components: [
      { es: "Etiqueta: poliéster reciclado 100%", en: "Label: 100% recycled polyester" },
      { es: "Hilo de costura: poliéster reciclado", en: "Sewing thread: recycled polyester" },
      { es: "Embalaje: cartón reciclado + bolsa compostable", en: "Packaging: recycled cardboard + compostable bag" },
    ],
  },
  traceability: {
    chain_of_custody: "Mass Balance + Segregación",
    chain_of_custody_en: "Mass Balance + Segregation",
    certifications: [
      { name: "GOTS", full_name: "Global Organic Textile Standard", certificate_number: "GOTS-2026-TR-001234", certifier: "Control Union", valid_until: "2027-01-31", scope: "Ginning + Hilatura", scope_en: "Ginning + Spinning", status: "vigente" as const, custody_model: "Segregación", custody_model_en: "Segregation", material_supported: "Algodón orgánico", material_supported_en: "Organic cotton", source_evidence: "Certificación GOTS", source_evidence_en: "GOTS certification", type: "custody" as const },
      { name: "GRS", full_name: "Global Recycled Standard", certificate_number: "GRS-ES-005678", certifier: "Textile Exchange", valid_until: "2026-12-31", scope: "Poliéster reciclado", scope_en: "Recycled polyester", status: "vigente" as const, custody_model: "Mass Balance", custody_model_en: "Mass Balance", material_supported: "Poliéster reciclado", material_supported_en: "Recycled polyester", source_evidence: "Certificación GRS", source_evidence_en: "GRS certification", type: "custody" as const },
      { name: "OEKO-TEX Standard 100", full_name: "OEKO-TEX Standard 100", certificate_number: "26.HTR.12345", certifier: "Hohenstein", valid_until: "2027-03-31", scope: "Producto final (Clase II)", scope_en: "Final product (Class II)", status: "vigente" as const, source_evidence: "Certificación OEKO-TEX Standard 100", source_evidence_en: "OEKO-TEX Standard 100 certification", type: "product_evidence" as const },
    ],
    audits: [
      { type: "SMETA 4P", date: "2025-11-15", result: "Aprobada con observaciones cerradas", result_en: "Approved with closed observations", critical: 0, minor: 2, minor_closed: 2, auditor: "SGS", facility: "Confección (Túnez)", facility_en: "Manufacturing (Tunisia)" },
    ],
  },
  durability: {
    wash_cycles: 50,
    tensile_strength_N: 250,
    color_fastness: "4/5",
    pilling_resistance: "4/5",
    care_instructions: {
      washing: { es: "30°C máximo, ciclo delicado", en: "Max 30°C, delicate cycle" },
      bleaching: { es: "No usar", en: "Do not use" },
      drying: { es: "Secadora a baja temperatura o tender", en: "Low temp dryer or hang dry" },
      ironing: { es: "110°C máximo, sin vapor", en: "Max 110°C, no steam" },
      dry_cleaning: { es: "No", en: "No" },
    },
    warranty: { duration_years: 2, coverage: "Defectos de fabricación", coverage_en: "Manufacturing defects" },
    repairability: {
      available: true,
      available_en: "Yes",
      recommended: "Costuras, dobladillos y pequeños daños",
      recommended_en: "Seams, hems and small damages",
      spare_parts: "No aplica",
      spare_parts_en: "Not applicable",
      warranty_years: 2,
      warranty_coverage: "Defectos de fabricación",
      warranty_coverage_en: "Manufacturing defects",
    },
  },
  environmental_impact: {
    carbon_footprint: {
      total_kg_co2eq: 8.5,
      breakdown: [
        { stage: "Materias primas", stage_en: "Raw materials", kg: 3.2, percentage: 37.6 },
        { stage: "Hilatura + Tejeduría", stage_en: "Spinning + Weaving", kg: 2.1, percentage: 24.7 },
        { stage: "Confección", stage_en: "Manufacturing", kg: 1.8, percentage: 21.2 },
        { stage: "Transporte", stage_en: "Transport", kg: 0.9, percentage: 10.6 },
        { stage: "Acabado + Packaging", stage_en: "Finishing + Packaging", kg: 0.5, percentage: 5.9 },
      ],
      methodology: "PEF",
      verification: "Quantis (2026-01-20)",
    },
    water_footprint: {
      total_liters: 1200,
      breakdown: [
        { stage: "Cultivo algodón", stage_en: "Cotton cultivation", liters: 950, percentage: 79.2 },
        { stage: "Procesos húmedos", stage_en: "Wet processes", liters: 200, percentage: 16.7 },
        { stage: "Otros", stage_en: "Other", liters: 50, percentage: 4.1 },
      ],
    },
    energy: {
      total_kwh: 12,
      sources: [
        { type: "Electricidad grid", type_en: "Grid electricity", kwh: 9, percentage: 75 },
        { type: "Gas natural", type_en: "Natural gas", kwh: 2, percentage: 17 },
        { type: "Renovables on-site", type_en: "On-site renewables", kwh: 1, percentage: 8 },
      ],
    },
    microplastics: {
      per_wash_mg: 0.12,
      lifetime_mg: 6,
      mitigation: "Filtro de microfibra recomendado",
      mitigation_en: "Microfiber filter recommended",
    },
  },
  end_of_life: {
    recyclability_index: 75,
    compostable: false,
    compostable_reason: 'Mezcla de fibras sintéticas',
    compostable_reason_en: 'Synthetic fiber blend',
    disposal_options: [
      { option: "Donación", option_en: "Donation", condition: "Prenda en buen estado", condition_en: "Garment in good condition" },
      { option: "Punto de recogida textil", option_en: "Textile collection point", type: "Contenedor naranja", type_en: "Orange container" },
      { option: "Recycling center", option_en: "Recycling center", note: "No vertedero", note_en: "No landfill" },
    ],
    take_back_program: {
      available: true,
      conditions: "Tienda física o envío por correo",
      conditions_en: "Physical store or mail return",
      source: "Política take-back",
      source_en: "Take-back policy",
      has_document: true,
    },
    collection_points: [
      { name: "EcoTextil Valencia", name_en: "EcoTextil Valencia", type: "Punto de recogida textil", type_en: "Textile collection point", use: "Reciclaje textil", use_en: "Textile recycling", address: "Av. Aragón 145, Valencia", distance: "1.2 km", coords: [39.47, -0.38] as [number, number], icon: "recycle" },
      { name: "Fundación Segunda Vida", name_en: "Second Life Foundation", type: "Donación", type_en: "Donation", use: "Reutilización de prenda en buen estado", use_en: "Reuse of garment in good condition", address: "Calle Colón 82, Valencia", distance: "2.4 km", coords: [39.48, -0.35] as [number, number], icon: "donation" },
      { name: "Centro de reciclaje municipal", name_en: "Municipal recycling center", type: "Centro de reciclaje", type_en: "Recycling center", use: "Gestión final del textil", use_en: "Final textile management", address: "Carrer dels Serrans 21, Valencia", distance: "3.1 km", coords: [39.46, -0.42] as [number, number], icon: "recycle" },
    ],
  },
  compliance: {
    reach: {
      status: "Compliant" as const,
      restricted_substances: 0,
      svhc_substances: 0,
      verification_date: "2026-02-01",
    },
    csrd: {
      applies: true,
      esrs_mapping: {
        E1: { es: "Huella de carbono disponible", en: "Carbon footprint available" },
        E2: { es: "Emisiones al aire/agua disponibles", en: "Air/water emissions available" },
        E3: { es: "Huella hídrica disponible", en: "Water footprint available" },
        E4: { es: "Origen de fibras disponible", en: "Fiber origin available" },
        E5: { es: "Reciclabilidad y fin de vida disponibles", en: "Recyclability and end-of-life available" },
      },
      export_formats: ["XBRL", "CSV"],
    },
    eudr: {
      applies: false,
      note: "Algodón no está en scope actual",
      note_en: "Cotton not in current scope",
    },
    espr: {
      status: "DPP Compliant" as const,
      delegated_act: "Textiles (esperado 2027)",
      delegated_act_en: "Textiles (expected 2027)",
      fields_covered: "35/35",
      data_carrier: "QR code GS1 Digital Link",
    },
  },
  metadata: {
    issue_date: "2026-06-07",
    last_update: "2026-06-07",
    version: "1.0",
    operator: {
      name: "Vela Textile SL",
      address: "Calle Ejemplo 123, 08001 Barcelona, España",
      address_en: "Example St 123, 08001 Barcelona, Spain",
      email: "compliance@velatextile.eu",
      phone: "+34 93 123 45 67",
      vat: "ESB12345678",
    },
    public_url: "https://dpp.velatextile.eu/vt-cam-001",
    qr_code: "GS1 Digital Link",
    data_format: "JSON-LD (schema.org/Product)",
    languages: ["ES", "EN"],
    accessibility: "WCAG 2.1 AA",
  },
};
